import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  team: React.ReactNode;
  dashboard: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children, team, dashboard }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container mx-auto">
          <section className="my-6">{children}</section>
          <section className="flex gap-6">
            {team}
            {dashboard}
          </section>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
